version: '3.8'
services:
  python_app:
    restart: unless-stopped
    build: 
      context: ./
      dockerfile: API/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./JMSPlant.db:/app/JMSPlant.db
    environment:
      - DATABASE_URL=sqlite:///./JMSPlant.db