name: Python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.1'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        
    - name: Run tests
      env:
        DATABASE: 'JMSPlant_test.db'
      run: |
        python DB/python/github_actions_DB.py
        python API/test_api.py
    
    - name: Delete JMSPlant_test.db
      run: rm -f JMSPlant_test.db
